language: node_js
node_js:
  - 12
sudo: required
services:
  - xvfb
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm install -g yarn
  - yarn
script:
  - yarn lint
  - yarn test
after_script:
  - yarn coveralls
