name: 🚀　Release
on:
  push:
    branches:
      - master
      - next
      - next-major
      - alpha
      - beta
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️　Checkout
        uses: actions/checkout@v2

      - name: 🚧　Install
        run: yarn install

      - name: 📦　Build
        run: yarn build

      - name: ✅　Test
        run: yarn test

      - name: 🔑　Generate Token
        uses: bubkoo/use-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          env_name: bot_token

      - name: 📦　Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          extends: '@bubkoo/semantic-release-config'
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ env.bot_token }}

      - name: 🎉　Setup Node.js with GitHub Package Registry
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
          scope: bubkoo

      - name: 🔀　Publish To GitHub Package Registry
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          sed -i 's/\("name"\:[[:space:]]*"\)\(html-to-image"\)/\1@bubkoo\/\2/' package.json
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
